name: 页面构建
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 工作流签出
        uses: actions/checkout@v4
      - name: 页面初始化
        uses: actions/configure-pages@v5
      - name: 统一配置
        run: |
          curl -o .vitepress/dist/favicon.ico https://www.qqzhi.cc/favicon.ico
      - name: IndexNow配置
        run: echo ${{secrets.INDEXNOW_KEY}} > .vitepress/dist/${{secrets.INDEXNOW_KEY}}.txt
      - name: 页面上传
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.vitepress/dist/'
      - name: 页面上线
        id: deployment
        uses: actions/deploy-pages@v4
      - name: IndexNow推送
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://blog.qqzhi.cc/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
